Feat/claire elastic test
lemoncloud-io/lemon-core pull request #153
Opened 2024-07-18 08:11 UTC by claire-lemon

test: test searchEngine Instances

2024-07-22 01:02 UTC, steve-lemon reviewed
코드 정리 좋아요. 좀더 개선해 봅시다.

2024-07-22 01:02 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.ts
> +                if (msg.startsWith('404 INDEX NOT FOUND')) throw new Error(`404 INDEX NOT FOUND - index:${indexName}`);
`404 NOT FOUND`으로 인식하니,
`404 NOT FOUND - index:${indexName}`
이렇게 합시다.

2024-07-22 01:02 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.ts
> +            if (version < 6.8) params.body.lang = 'painless';
`version < 6.8` 인지 `version =< 6.8` 이거인지 다시 확인해줘요

2024-07-22 01:28 UTC, claire-lemon commented on src/cores/elastic/elastic6-service.ts
> +            if (version < 6.8) params.body.lang = 'painless';
root로부터 버전 확인했는데 아래와 같아서 `version < 6.8`로 했습니다!
    '6.2': 'https://localhost:8443', // "6.2.3"
    '6.8': 'https://localhost:8683', // "7.10.2"
    '7.1': 'https://localhost:9683', // -
    '7.2': 'https://localhost:9072', // "7.1.1"
    '7.10': 'https://localhost:9710', // "7.10.2"
    '2.13': 'https://localhost:9213', // "7.10.2"

2024-07-22 01:47 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.ts
> +        const versionInfo: string = response.body.version.number;
recommended
`const versionInfo = $U.S(response?.body?.version?.number)`

2024-07-22 01:51 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.ts
> +            if (version < 6.8) params.body.lang = 'painless';
keep `< 7.0`

2024-07-23 01:15 UTC, steve-lemon requested changes
코드 정리하고 가쥬

2024-07-23 01:15 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.ts
>                  if (msg.startsWith('404 NOT FOUND')) throw new Error(`404 NOT FOUND - id:${id}`);
`404` 에러발생시 원인 파악을 좀더 쉽게... -> 힌트를 좀 더 추가하면 좋음 => 에러원인 구분가능해야함.
-> 내부에러가 발생한 이유가 있음 
1. item이 없는 경우
2. index가 없는 경우

2024-07-23 01:15 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.spec.ts
> +export const canBasicCRUD = async (service: Elastic6Service<any>): Promise<void> => {
rename `verifyBasicCRUD`

2024-07-23 01:15 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.spec.ts
> +    it('should pass basic CRUD w/ real server(2.13)', async () => {
`should pass basic CRUD w/ open-search server(2.13)`

2024-07-23 01:19 UTC, steve-lemon commented
추가적으로 검토할일
`@elastic/elasticsearch` 요거 업데이트하기.

2024-07-24 00:25 UTC, claire-lemon commented
어제 리뷰해주셨던 부분들 수정했습니다.

1. '2.13' 버전 특정지었던 부분들을 'version < 7' 범위 적용
2. params: any 부분에서, any 안쓰도록 interface 새로 추가 후 적용
3. 테스트 메소드 이름 수정

추가적으로,
searchRaw의 response에서 os2.13만 '_type': '_doc'가 존재하지 않아 테스트를 통과하지 못하고 있습니다.

ElasticSearch Documentation에 따르면, 'typeless APIs will return the dummy type _doc in the response'
7.X 버전에서는 더미 데이터로 '_type': '_doc'를 return 한다고 적혀있지만
최신 openSearch 버전에서는 더미데이터 '_type': '_doc'를 제외한 채로 return하는 것 같습니다.

버전을 명확하게 나누기 위해 좀 더 찾아보겠습니다!

2024-07-24 01:14 UTC, steve-lemon requested changes
수고했어요~

2024-07-24 01:14 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.spec.ts
>          console.error('! err =', GETERR(e));
`console.error('! err =', e);` 이게 더 나을듯. 그래야 상세 정보 알 수 있음

2024-07-24 01:14 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.ts
> +interface ElasticParams {
코멘트 달아주고 body에 대해서는 모르지만, 추후를 위해서 아래와 같이 합시다.
`ElasticParams<T extends object = any>{ body: T }`

2024-07-24 01:14 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.ts
> +interface ElasticSearchParams {
여기도 마찬가지

2024-07-24 01:14 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.ts
> +            const info = await this.client.info();
혹시 open-search 인지 구분할 수 있는지도 알아봐줘요

2024-07-24 01:14 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.ts
> +            throw new Error('Fail to parse: ' + version);
`Error` 발생시 패턴이 있어요. 이 경우. 아래와 같이 처리해줘요
`@version[${version}] is invalid - fail to parse`

2024-07-24 01:14 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.ts
> +interface ParsedVersion {
마찬가지, 코멘트 항상 달아줘요

2024-07-24 02:33 UTC, claire-lemon commented
1. 에러 관련된 부분 수정
: 로깅 더 상세하게 할 수 있도록, 에러 발생시 패턴대로 처리하도록
2. comment 작성
3. openSearch 버전이 2.0 이상이면 '_type': '_doc' 빼도록
참고: https://github.com/opensearch-project/OpenSearch/issues/2979

리뷰해주신 부분들 수정했습니다!

2024-07-25 04:56 UTC, steve-lemon approved these changes
LGTM

2024-07-25 04:56 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.spec.ts
> +        console.error('! err =', e);
괜찮은데, 왼만하면 console.log | warn | error 같은 콘솔 직접 사용안하도록

2024-07-25 04:56 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.ts
> +        return this.version < 5;
`this.version < 6;`

2024-08-01 01:11 UTC, claire-lemon commented
1. 신규 필드에 대한, 자동 매핑 생성과 데이터 미스매칭에 따른 에러 변화 확인
    -  'null' 저장하기
        - string -> null, '' -> null
        - number(long|float) -> null
        - [] -> null
    - 타입 변경(long -> float) 시 
    - array[] 이용시 타입 변경
    
2. inner-object update w/ null support
    내부 객체가 아래와 같이 업데이트 됨을 확인
    1) { a: 1 } -> { a:null } >> final = { a:null }
    2) { a:1 } -> { b:null } >> final = { a:1, b:null }
    
3. auto-indexing w/ tokenizer.
    ‘name’에 2단어 이상의 값을 저장
    - name을 키워드로 검색
    - name을 한글 키워드로 검색
    
4. 각 client instance info [samples/<version>/info.json]에 저장

2024-08-01 04:19 UTC, steve-lemon commented
추가로 `array[]` 이용시 타입 다른것도 테스트
- ex) aa:[] -> aa:['a'] -> aa:['a',1] -> aa:[null] -> aa:[1.1] -> aa:[{b:a}]

2024-08-05 09:18 UTC, claire-lemon commented
### 미스매치 타입 관련 수정
1. array 내부 요소 타입 변경 테스트 추가
2. update시 발생하는 에러들을 각 버전별로 저장 후, $ERROR 테스트
3. 자동 매핑된 타입들을 확인하기 위한 getIndexMapping 메소드 추가

### Error Response 관련 수정
1. 더 구체적인 에러 발생 원인을 알 수 있도록 root_cause를 ErrorResponse에 추가

기존 에러메세지
> `400 MAPPER PARSING - mapping-parse-exception`

수정한 에러메세지
> `400 MAPPER PARSING - object mapping for [nested_field] tried to parse field [nested_field] as object, but found a concrete value`

2024-08-05 10:25 UTC, steve-lemon approved these changes
LGTM
- 잘하고 잇어유~

2024-08-05 10:25 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.spec.ts
> +    const properties2 = version < 7 ? mapping2._doc.properties : mapping2.properties;
`mapping2?._doc?.properties` 처럼 항상 null 이 있을수 있음을 고려해줘요.

2024-08-05 10:25 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.ts
> +        if (!mapping) throw new Error(`Mapping for index <${indexName}> not found - ${$U.json(res)}!`);
에러텍스트를 정해진 패턴에 맞게 해줘요.
1. `@param (some) is invalid - x.x.x.`
2. `.property (object) is invalid - sdfjasldjfalj `

2024-08-05 10:25 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.ts
> +            const $e = new Error(`${E.status} ${E.reason.type} - ${E.reason.reason || E.message}`);
`E?.reason?.reason` 처럼 항상 nullable 조심하기

2024-08-07 02:22 UTC, claire-lemon commented
1. 버전을 동적으로 가져오는 것에 대한 성능 저하 이슈 수정
    
    > instance 생성시 root 버전을 가져오고 this.parsedVersion에 저장하도록 수정
    
2. totalSummary 테스트 추가
    > totalSummary 진행시 시간이 너무 오래걸리는 이슈가 있습니다.
    - 2만개의 데이트 bulk 업데이트
    - search test 진행
    - scanAll test 진행
    429 too many requests 에러로 인해 테스트가 되지 않아, 429 에러가 발생한다면 일정 시간 이후 retry하도록 했습니다.
3. connection이 없어도 테스트가 되도록 수정
6. 더미 데이터들에 대한 description 추가
7. info.json을 option에 따라 data/samples에 저장할 수 있도록 추가
8. test coverage를 높이기 위한 parseVersion 에러 테스트 추가

2024-08-07 04:09 UTC, steve-lemon reviewed
LGTM
- 벌크 테스트 좋아요~ 👍

2024-08-07 04:09 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.spec.ts
> +    const parsedVersion: ParsedVersion = service.parsedVersion;
`Elastic6Option.verion` 있으니, 이것을 파싱해서 써먹는게 어때요?
`service.getVersion()`은 호환성 테스트에 써먹는걸루 하고.
이게 serverless 환경이라, stateless 에 맞춰줘요.

2024-08-07 04:09 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.spec.ts
> +        count: i + 1,
카운트를 10의 나머지로해서, aggregation에서 확인하도록하죠
`count: (i + 1)%10`

2024-08-07 04:09 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.spec.ts
> +                count: {
sort는 `id.keyword` 으로

2024-08-07 04:09 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.spec.ts
> +        total: version < 7 ? 20000 : 10000,
이건 설명이 필요할듯

2024-08-07 04:09 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.spec.ts
> +                    ...(service.version >= 2 && service.isOpenSearch ? {} : { _type: '_doc' }),
이부분은 공통으로 빼줘요

2024-08-07 09:07 UTC, claire-lemon commented
1.  Elastic6Option.version을 version으로 사용하도록 수정
    6.8(root version = 7.10)이 기존에 존재하던 엔드포인트이었어서 아래와 같이 6.8과 1.1을 각각 둔 상태로 rootVersion을 통해 작업 했었는데,
    Elastic6Option.version으로부터 버전을 받아오며 6.8은 테스트가 되지 않아 관련 테스트들은 지우고 1.1 테스트만 남겨두었습니다.
```
    `6.8': 'https://localhost:8683', // run alias lmes68
    //* open-search */
    '1.1': 'https://localhost:8683', // run alias lmes68
```
2. totalSummary의 search 테스트의 common response 부분 수정
3. parseVersion() 에러 핸들링 수정
    기존: `throw Error` >> 수정된 방식: `{error: ''}`
    동기 함수에서 에러를 catch 하지못해 테스트가 강제로 종료 되는 문제가 발생했습니다.
    따라서 에러가 발생하면 response에 error를 포함하도록 수정했지만, 다른 방법이 있다면 수정하도록 하겠습니다..

2024-08-08 04:38 UTC, steve-lemon reviewed
`options?: { throwable?: boolean }` 으로 에러 발생 컨트롤 하기

2024-08-08 09:02 UTC, claire-lemon commented
1. `options?: { throwable?: boolean } `으로 에러 발생 컨트롤 하도록 수정
2. test coverage를 높이기 위한 테스트 추가
    - describe 테스트
    > uuid, createdDate 등과 같이 테스트마다 다르게 나오는 값을 제외한 후, 나머지 properties들을 테스트
    - flush 테스트
    > `_shards`내의 `successful`의 값이 같은 버전임에도 테스트마다 다르게 나와 `_shards`가 `failed`, `successful`, `total`을 포함하는지만 테스트
    - 404 not found index 테스트

2024-08-09 00:19 UTC, steve-lemon requested changes
LGTM, 전반적으로 좋아요. 몃가지 부분 수정후 배포갑시다.
1. `parseVersion()` throws
2. use `expect2()` (check the implement)
3. self-diagnosis w/ checking version
4. backward compatible to make common service.
5. auto dump `info.json` in format like `os1.2` (how to detect os vs es?)

2024-08-09 00:19 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.spec.ts
> +                    return {
여긴 그냥, `return rest`

2024-08-09 00:19 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.spec.ts
> +    if (version < 7 && !service.isOpenSearch) {
이 컨디션을 한줄짜리 함수로 만든다면?

2024-08-09 00:19 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.ts
> +    public parseVersion(version: string): ParsedVersion {
improve w/ throw

2024-08-09 00:19 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.ts
> +                if (msg.startsWith('429 UNKNOWN')) {
retry 부부분은 options으로 빼줘야할듯.

2024-08-09 00:19 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.ts
> -        version?: string;
여긴 string -> number 으로 바꾸면 안될듯

2024-08-09 08:07 UTC, claire-lemon commented
1. parsedVersion 수정
    
    > Semantic Versioning (SemVer) rules대로 parse하고, 기타 버전 정보들 포함하도록 수정
    > 
2. generateSearchResult 수정
    
    > 에러를 catch할 때, 같은 조건으로 하도록 수정
    > 
3. executeSelfTest 추가
    
    > option의 버전과 root 버전이 같은지 확인하는 테스트 추가
    > 
4. info.json path 수정

2024-08-09 09:10 UTC, steve-lemon approved these changes
LGTM

2024-08-19 09:06 UTC, claire-lemon commented
1. bulk data 크기, 아이템 수정
```
    const dataset = Array.from({ length: 15000 }, (_, i) => {
        return {
            id: `${i + 1}`,
            name: `employee ${i + 1}`,
            department: departmentName[(i + 1) % 10],
            salary: salaries[(i + 1) % 6],
            count: (i + 1) % 10,
            company: companies[(i + 1) % 3],
        };
    });
```
2. 수정한 데이터로 totalSummaryTest, aggregationTest 진행
totalSummaryTest는 기존과 동일, aggregationTest는 terms와 terms+terms로 테스트

추가적으로,
데이터를 bulk하는 과정에서도 429 too many response Error가 뜹니다.
따라서 데이터 수를 20000 -> 15000으로 줄여 테스트 했습니다.

2024-08-19 10:30 UTC, steve-lemon commented
네 좋아요

2024-08-21 09:19 UTC, claire-lemon commented
1. bulkDummyData에 employee name 추가
    bulk upload한 아이템으로 search with filter 테스트를 하기 위해, 각 employee의 이름이 생성돼 저장되도록 수정했습니다.

2. searchFilterTest 추가
- 키워드 검색 테스트 : name으로 검색 테스트
- 범위 검색 테스트 : salary로 범위 검색 테스트
- empty item 저장 및 검색 테스트:
    `''`, `null`, `[]`, `아이템을 아예 저장 X` ,  총 4 경우로 검색을 테스트, {}는 매핑 타입 오류 발생
    추가적으로 매핑 타입 확인하는 부분도 추가했습니다.

2024-08-23 02:06 UTC, steve-lemon reviewed
테스트 목적 -> 호환성체크 -> 검색엔지 업그레이드
1. 버전별로 search 결과 차이가 있는지 확인
2. 키워드/한글 토큰나이저 작동 호환성여부
3. 업그레이드 해도 문제없냐? --> ES/OS **호환성** 리포트 참고

2024-08-27 01:27 UTC, steve-lemon reviewed
LGTM

2024-08-27 07:38 UTC, claire-lemon commented on src/cores/elastic/elastic6-service.spec.ts
> +        last: ['employee 10000'],
문자열로 sort한 후 5개의 docs를 불러왔기 때문입니다.
그 결과, 정렬된 값들 중 상위 5개인 'employee 1', 'employee 10', 'employee 100', 'employee 1000', 'employee 10000' 가 return 되었고, `last: ['employee 10000'],`가 되었습니다.

> 문자열 정렬 예시
[ '1', '6', '100', '52', '1000', '101' ] -- 문자열 정렬 -> [ '1', '100', '1000', '101', '52', '6']

만약 문자열 속 숫자를 실제 숫자처럼 정렬하고 싶다면, `natural sort order`을 사용 할 수 있습니다.
natural sort order는 문자열에 포함된 숫자를 문자 그대로가 아닌 실제 숫자값으로 인식하여 정렬하는 방식입니다. 정규식을 사용하여 문자열 내의 숫자를 추출하고, 이를 기준으로 정렬합니다.

2024-08-28 00:59 UTC, claire-lemon commented
1. query-service 각 버전별 테스트 추가
2. _score값 확인을 위한 matchSearchTest 추가
    - filter term search시에는 _score가 0으로 뜹니다.
    - match search 시에는 버전 별로 _score가 다르게 계산됩니다. 
    특히 `isLatestOS2` 의 경우, 어제와 오늘 _score가 다르게 나와, 분기했던 부분을 아래 코드처럼 주석처리했습니다. 왜 2.13 버전만 어제랑 오늘 다른 score 값을 갖는지는 잘 모르겠어서 조금 공부 더 해보겠습니다!
```

    // if (service.isLatestOS2) {
    //     expect2(() => matchSearchResult.list).toEqual(expectedMatchList2);
    //     expect2(() => matchSearchResult.last).toEqual([
    //         expectedMatchList2[expectedMatchList2.length - 1]._score,
    //         `${expectedMatchList2[expectedMatchList2.length - 1].id}`,
    //     ]);
    // } else
    if (service.isOldES6) {
        expect2(() => matchSearchResult.list).toEqual(expectedMatchList6);
        expect2(() => matchSearchResult.last).toEqual([
            expectedMatchList6[expectedMatchList6.length - 1]._score,
            `${expectedMatchList6[expectedMatchList6.length - 1].id}`,
        ]);
    } else {
        expect2(() => matchSearchResult.list).toEqual(expectedMatchList);
        expect2(() => matchSearchResult.last).toEqual([
            expectedMatchList[expectedMatchList.length - 1]._score,
            `${expectedMatchList[expectedMatchList.length - 1].id}`,
        ]);
    }

```

2024-08-28 01:14 UTC, steve-lemon commented
> 1. query-service 각 버전별 테스트 추가
> 2. _score값 확인을 위한 matchSearchTest 추가
>    
>    * filter term search시에는 _score가 0으로 뜹니다.
>    * match search 시에는 버전 별로 _score가 다르게 계산됩니다.
>      특히 `isLatestOS2` 의 경우, 어제와 오늘 _score가 다르게 나와, 분기했던 부분을 아래 코드처럼 주석처리했습니다. 왜 2.13 버전만 어제랑 오늘 다른 score 값을 갖는지는 잘 모르겠어서 조금 공부 더 해보겠습니다!
> 
> ```
> 
>     // if (service.isLatestOS2) {
>     //     expect2(() => matchSearchResult.list).toEqual(expectedMatchList2);
>     //     expect2(() => matchSearchResult.last).toEqual([
>     //         expectedMatchList2[expectedMatchList2.length - 1]._score,
>     //         `${expectedMatchList2[expectedMatchList2.length - 1].id}`,
>     //     ]);
>     // } else
>     if (service.isOldES6) {
>         expect2(() => matchSearchResult.list).toEqual(expectedMatchList6);
>         expect2(() => matchSearchResult.last).toEqual([
>             expectedMatchList6[expectedMatchList6.length - 1]._score,
>             `${expectedMatchList6[expectedMatchList6.length - 1].id}`,
>         ]);
>     } else {
>         expect2(() => matchSearchResult.list).toEqual(expectedMatchList);
>         expect2(() => matchSearchResult.last).toEqual([
>             expectedMatchList[expectedMatchList.length - 1]._score,
>             `${expectedMatchList[expectedMatchList.length - 1].id}`,
>         ]);
>     }
> ```

어떻게 다르게 나오나요?! 정확한 스코어보다는, score 정렬시 순서가 일정하게 유지되는지로 보는게 나을지도..

2024-08-28 02:20 UTC, Yeeun411 commented
```
//* 1.2 Test by keyword (match query)
    const $matchSearch: SearchBody = {
        size: 3,
        query: {
            match: {
                name: 'jordan',
            },
        },
        aggs: {
            employees_with_name_Jordan_per_company: {
                terms: {
                    field: 'company.keyword',
                },
            },
        },
        sort: [
            {
                _score: {
                    order: 'desc',
                },
                'id.keyword': {
                    order: 'asc',
                    missing: '_last',
                },
            },
        ],
    };

// 버전 7.x에서 _score로 정렬시 나오는 결과, 현재 2.13 버전도 아래처럼 나옵니다!
    const expectedMatchList: Array<TestList> = [
        {
            _id: 'employee 1001',
            _score: 2.0919745,
            company: 'C',
            count: 1,
            department: 'HR',
            id: 'employee 1001',
            name: 'Jordan Hayden Harper',
            salary: 20000,
        },
        {
            _id: 'employee 10041',
            _score: 2.0919745,
            company: 'A',
            count: 1,
            department: 'HR',
            id: 'employee 10041',
            name: 'Jordan Reese Cameron',
            salary: 11500,
        },
        {
            _id: 'employee 10073',
            _score: 2.0919745,
            company: 'C',
            count: 3,
            department: 'Marketing',
            id: 'employee 10073',
            name: 'Jordan Hayden Harper',
            salary: 20000,
        },
    ];

// 버전 6.x에서 _score로 정렬시 나오는 결과
    const expectedMatchList6: Array<TestList> = [
        {
            _id: 'employee 10033',
            _score: 2.0947309,
            company: 'B',
            count: 3,
            department: 'Marketing',
            id: 'employee 10033',
            name: 'Jordan Parker Bailey',
            salary: 5000,
        },
        {
            _id: 'employee 10089',
            _score: 2.0947309,
            company: 'A',
            count: 9,
            department: 'Logistics',
            id: 'employee 10089',
            name: 'Jordan Reese Bailey',
            salary: 11500,
        },
        {
            _id: 'employee 10121',
            _score: 2.0947309,
            company: 'C',
            count: 1,
            department: 'HR',
            id: 'employee 10121',
            name: 'Jordan Hayden Mason',
            salary: 20000,
        },
    ];
// 버전 2.x에서 _score로 정렬시 나오는 결과, 어제는 이렇게 나왔었습니다ㅠ
    const expectedMatchList2: Array<TestList> = [
        {
            _id: 'employee 10009',
            _score: 2.1102757,
            company: 'B',
            count: 9,
            department: 'Logistics',
            id: 'employee 10009',
            name: 'Jordan Parker Mason',
            salary: 5000,
        },
        {
            _id: 'employee 10049',
            _score: 2.1102757,
            company: 'C',
            count: 9,
            department: 'Logistics',
            id: 'employee 10049',
            name: 'Jordan Hayden Ellis',
            salary: 20000,
        },
        {
            _id: 'employee 10097',
            _score: 2.1102757,
            company: 'C',
            count: 7,
            department: 'Production',
            id: 'employee 10097',
            name: 'Jordan Hayden Cameron',
            salary: 20000,
        },
    ];
```

2024-08-28 02:27 UTC, steve-lemon commented
그러게요. `_score`가 일정하게 나올법도 한데, 궁금하군요

2024-08-28 02:29 UTC, claire-lemon commented
왜 그런지 찾아보겠습니다!

2024-08-28 05:21 UTC, claire-lemon commented
버전 별 score 계산 explanation

// Version 6.2
```
{
  "details": [
    {
      "description": "score(doc=11,freq=1.0 = termFreq=1.0), product of:",
      "details": [
        {
          "description": "idf, computed as log(1 + (docCount - docFreq + 0.5) / (docFreq + 0.5)) from:",
          "details": [[Object], [Object]],
          "value": 2.0947309
        },
        {
          "description": "tfNorm, computed as (freq * (k1 + 1)) / (freq + k1 * (1 - b + b * fieldLength / avgFieldLength)) from:",
          "details": [[Object], [Object], [Object], [Object], [Object]],
          "value": 1
        }
      ],
      "value": 2.0947309
    }
```

// version 7.x
```
{
  "details": [
    {
      "description": "score(freq=1.0), product of:",
      "details": [
        {
          "description": "boost",
          "details": [],
          "value": 2.2
        },
        {
          "description": "idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:",
          "details": [[Object], [Object]],
          "value": 2.0919745
        },
        {
          "description": "tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:",
          "details": [[Object], [Object], [Object], [Object], [Object]],
          "value": 0.45454544
        }
      ],
      "value": 2.0919745
    }
  ],
}
```

// Version 2.13
```
{
  "details": [
    {
      "description": "score(freq=1.0), computed as boost * idf * tf from:",
      "details": [
        {
          "description": "boost",
          "details": [],
          "value": 2.2
        },
        {
          "description": "idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:",
          "details": [[Object], [Object]],
          "value": 2.0919745
        },
        {
          "description": "tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:",
          "details": [[Object], [Object], [Object], [Object], [Object]],
          "value": 0.45454544
        }
      ],
      "value": 2.0919745
    }
  ],
}
```

2024-08-28 08:13 UTC, steve-lemon commented
저 스코어 보분은 소스 코멘트로 남겨줘요. 검증은 좀 힘들수도 있어보이네요.

2024-09-02 03:07 UTC, claire-lemon commented
1. define the response type in detail see `SearchResponse`
2. 빈문자열 테스트 `{ empty: '' }` 추가하여 개선
3. update시 모든 docs를 대체해 저장하는 indexItem 추가 + 관련 간단 테스트 추가
    > es guide에서 index라는 api로 업데이트하면 overwriting이 가능함을 확인했습니다.
    updateItem 로직을 client.update에서 client.index로 수정하지않고, 일단은 indexItem()을 새로 추가해 overwrite 기능도 사용할 수 있도록 추가한 상태입니다.
     만약 update 기능을 index()를 활용하는 방법으로 리팩토링해야한다면 그렇게 다시 수정하도록 하겠습니다!
4. searchRaw() 대신 search()로 호환성 유지하면 searchTest 하도록 수정
5. `//!`를 `//*`로 수정

2024-09-03 01:23 UTC, steve-lemon commented
1. `updateItem()` 이 잘 작동하도록 코드개선
2. `ElasticIndexService` 슈퍼 클래스 정의하기
3. `lemon-backend-docs` 에 문서 정리하면서.

2024-09-05 07:10 UTC, claire-lemon commented
1. updateItem 개선
    1. increment가 제대로 작동하도록 script 수정
    2. updateItem시 문서가 overwrite 되도록 관련 script 추가 작성 >> 문서 단위의 원자성 보장
    3. 일관성과 격리성 보장을 위해 `_seq_no`와 `_primary_term` param을 설정하여 update하도록 수정
2. `ElasticIndexService` 클래스 생성
    1. Elastic6Service가 이를 상속받도록 수정 >> 호환성 문제 없음 확인

2024-09-09 09:01 UTC, claire-lemon commented
1. updateItem 수정
    1. index()를 활용한 update overwrite
        
        script overwrite 기능에 의한 업데이트 성능 저하가 우려돼, index()를 활용하는 방식으로 코드를 수정했습니다.
        각각의 코드(script를 활용한 업데이트, index를 활용한 업데이트)로 basicCRUDTest update 부분의 테스트 소요 시간을 측정해보았는데, 적게는 0.05ms, 많게는 0.4ms까지 차이가 나는 것을 확인했습니다. 따라서 더 퍼포먼스가 좋은 index를 활용하는 방식으로 수정했습니다
        
    2. 낙관적 동시성 제어
        1. 6.0 이후부터는 _version이 아닌 _seq_no, _primary_term으로 낙관적 동시성을 제어함을 확인했습니다. 따라서  _seq_no로 개별 작업 단위의 동시성을 제어하고, _primary_term로 샤드 수준의 동시성을 제어할 수 있도록 했습니다.
2. doTest로 테스트 함수 호출 부분 모듈화
    1. 버전 별로 테스트 함수들을 호출하는 부분이 길고 중복된다고 판단해  doTest()로 대체했습니다.
3. comment 추가
    1. comment가 없었거나 부족하다고 느껴지는 부분들에 comment를 추가했습니다.

2024-09-30 00:32 UTC, claire-lemon commented
1. _ver()로 버전 잘 업데이트되는지 확인하도록
2. extra의 경우 overwrite되도록
3. increment array testcase 추가
4. ElasticIndexService 추상화
5. test에서 any 사용하지 않도록 CRUDModel interface 추가
    GeneralItem은 null이나 undefined를 지원하지않아서 optional 처리가 되지 않습니다.
    `$id?: string | any; ` 따라서 이런 식으로 해뒀는데, 보기 안좋아서 다른 방법이 있으면 수정해보겠습니다!

2024-10-14 14:05 UTC, steve-lemon approved these changes
LGTM

2024-10-14 14:05 UTC, merged