fix: fix 'fail to execute script` err
lemoncloud-io/lemon-core pull request #164
Opened 2024-10-17 12:30 UTC by claire-lemon

### 문제 상황
> 400 ILLEGAL ARGUMENT - failed to execute script

```
Object.entries(item).forEach(([key]) => {
                scripts.push(`ctx._source.${key} = params.item.${key};`);
            });
```
위 코드와 같은 scripts를 통해 업데이트가 이뤄지는데,
script가 특수기호`(eg. $)`를 인식하지 못하고 `fail to execute` 에러를 return 하는 것을 확인했습니다.

따라서 관련 스크립트를 수정하고, 에러가 발생한 데이터로 테스트 코드를 간단하게 추가했습니다.
더 다양한 테스트들은 이어서 추가하도록 하겠습니다.

```
ex) 에러가 발생하지 않는 경우
await service.saveItem( id, { account: { id: '1', openId: '1' }});
await service.updateItem( id, { account: { id: '2', openId: '2` }});
```
```
ex) 에러가 발생하는 경우
await service.saveItem( id, { account$: { id: '1', openId: '1' }});
await service.updateItem( id, { account$: { id: '2', openId: '2` }});

>> 400 ILLEGAL ARGUMENT - failed to execute script
```

2024-10-17 13:12 UTC, steve-lemon reviewed
아하.. 그럼, 필드이름때문에 그런간가요?
(샘플데이터는 초기 push할때 미리 처리해줘요)

2024-10-17 13:17 UTC, steve-lemon requested changes
see comments

2024-10-17 13:17 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.spec.ts
> +        await service.saveItem('T1070', {
변경된 부분이 노출되도록 코드 개선해줘요.
example:
```
const _id = 'T1070`
const data1 = { id: 'a', ... }
expect2(await service.saveItem(_id, { ...data1 })).toEqual({ ...data1, _id, $Id: _id })
```

2024-10-17 13:17 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.spec.ts
> +    expect2(await service.readItem('T1070')).toEqual({
read-back 부분도 원본이랑 같음

2024-10-17 13:17 UTC, steve-lemon commented on src/cores/elastic/elastic6-service.spec.ts
> +                airfob$: {
여기서는 원본데이터에서 `airfob$`만 추가된듯한데, 이것도 마찬가지.

2024-10-17 13:19 UTC, claire-lemon commented
슬랙에 태그해주신 추가 예제와 내부 객체 관련한 테스트들 더 확인해보고, 커멘트 달아주신 부분들도 수정하겠습니다!

2024-10-21 04:54 UTC, claire-lemon commented
1. updateItem 시 에러 메세지에 script 에러 발생 이유가 포함되도록 수정
2. update extra$ to null 테스트 추가 ( 에러 발생하지 않음 )
3.  '$'로 인해 발생했던 'invalid character error' 에러 로그를 samples/os1.2에 저장
4. type mismatch로 인해 발생한 script 에러 로그를 samples/os1.2에 저장

2024-10-21 04:56 UTC, claire-lemon reviewed
1. updateItem 시 에러 메세지에 script 에러 발생 이유가 포함되도록 수정
2. update extra$ to null 테스트 추가 ( 에러 발생하지 않음 )
3. '$'로 인해 발생했던 'invalid character error' 에러 로그를 samples/os1.2에 저장
4. type mismatch로 인해 발생한 script 에러 로그를 samples/os1.2에 저장

2024-10-21 05:46 UTC, steve-lemon approved these changes
LGTM

2024-10-21 05:48 UTC, merged